# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gifts',
            name='attribute',
        ),
        migrations.AddField(
            model_name='gifts',
            name='prim_attr',
            field=models.ManyToManyField(related_name='prim_attr', to='main.Attribute'),
        ),
        migrations.AddField(
            model_name='gifts',
            name='sec_attr',
            field=models.ManyToManyField(related_name='sec_attr', to='main.Attribute'),
        ),
    ]
