# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161213_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gifts',
            old_name='gift_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='gifts',
            name='gift_price',
        ),
        migrations.AddField(
            model_name='gifts',
            name='img_url',
            field=models.URLField(default='http'),
        ),
        migrations.AddField(
            model_name='gifts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='gifts',
            name='url',
            field=models.URLField(default='http'),
        ),
    ]
