# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161213_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='select',
            field=models.IntegerField(default=1),
        ),
    ]
